services:
  dragonfly:
    image: dragonflydb/dragonfly:v1.27.1
    command: ["--logtostderr"]
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: bidengine
      POSTGRES_USER: bidengine
      POSTGRES_PASSWORD: bidengine
    ports:
      - "5432:5432"

  kafka:
    image: confluentinc/cp-kafka:8.1.1
    container_name: transactional_outbox_pattern_demo-kafka-1
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9094
      # Localhost for your IDE, 'kafka' for other containers
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER://kafka:9093,LISTENER_HOST://localhost:9092
      KAFKA_LISTENERS: CONTROLLER://kafka:9094,LISTENER_DOCKER://kafka:9093,LISTENER_HOST://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,LISTENER_DOCKER:PLAINTEXT,LISTENER_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      # Replace with a stable base64 UUID from "bin/kafka-storage.sh random-uuid" if needed
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

